package NumberModule;


/**
* NumberModule/NumberServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Admin/Desktop/pism5/src/main/java/NumberService.idl
* 28 марта 2023 г. 10:19:31 MSK
*/

abstract public class NumberServiceHelper
{
  private static String  _id = "IDL:NumberModule/NumberService:1.0";

  public static void insert (org.omg.CORBA.Any a, NumberModule.NumberService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static NumberModule.NumberService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (NumberModule.NumberServiceHelper.id (), "NumberService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static NumberModule.NumberService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NumberServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, NumberModule.NumberService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static NumberModule.NumberService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NumberModule.NumberService)
      return (NumberModule.NumberService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      NumberModule._NumberServiceStub stub = new NumberModule._NumberServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static NumberModule.NumberService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof NumberModule.NumberService)
      return (NumberModule.NumberService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      NumberModule._NumberServiceStub stub = new NumberModule._NumberServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
