package NumberModule;


/**
* NumberModule/NumberService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Admin/Desktop/pism5/src/main/java/NumberService.idl
* 28 марта 2023 г. 10:19:31 MSK
*/

public interface NumberService extends NumberServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface NumberService
