package NumberModule;

/**
* NumberModule/NumberServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Admin/Desktop/pism5/src/main/java/NumberService.idl
* 28 марта 2023 г. 10:19:31 MSK
*/

public final class NumberServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public NumberModule.NumberService value = null;

  public NumberServiceHolder ()
  {
  }

  public NumberServiceHolder (NumberModule.NumberService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NumberModule.NumberServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NumberModule.NumberServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NumberModule.NumberServiceHelper.type ();
  }

}
