package NumberModule;


/**
* NumberModule/NumberServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Admin/Desktop/pism5/src/main/java/NumberService.idl
* 28 марта 2023 г. 10:19:31 MSK
*/

public interface NumberServiceOperations 
{
  void addNumber (double num);
  String getNumbers ();
} // interface NumberServiceOperations
