package NumberModule;


/**
* NumberModule/NumberServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Admin/Desktop/pism5/src/main/java/NumberService.idl
* 28 марта 2023 г. 10:19:31 MSK
*/

public abstract class NumberServicePOA extends org.omg.PortableServer.Servant
 implements NumberModule.NumberServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addNumber", new java.lang.Integer (0));
    _methods.put ("getNumbers", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // NumberModule/NumberService/addNumber
       {
         double num = in.read_double ();
         this.addNumber (num);
         out = $rh.createReply();
         break;
       }

       case 1:  // NumberModule/NumberService/getNumbers
       {
         String $result = null;
         $result = this.getNumbers ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:NumberModule/NumberService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public NumberService _this() 
  {
    return NumberServiceHelper.narrow(
    super._this_object());
  }

  public NumberService _this(org.omg.CORBA.ORB orb) 
  {
    return NumberServiceHelper.narrow(
    super._this_object(orb));
  }


} // class NumberServicePOA
